### ISSUE TITLE
guid creation in the frontend

### ISSUE THREAD

**Issue by paulvanbladel** [TomasEkeli/ToDolittle#7]
The @dolittle/core javascript module calculates guids based on Math.random().
Not sure how important it is to have no collisions for the correlationId, but maybe there is already stuff available that can dot this as well:
e.g.
https://github.com/kelektiv/node-uuid

**Comment by TomasEkeli** [comment]
Please take this up as an issue in https://github.com/dolittle-interaction/JavaScript.Client (this is not a sample-issue)
